apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.pco.plusserver.com
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/{{ include "pco-reseller-operator.fullname"
      . }}-serving-cert'
    controller-gen.kubebuilder.io/version: v0.10.0
  labels:
  {{- include "pco-reseller-operator.labels" . | nindent 4 }}
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: '{{ include "pco-reseller-operator.fullname" . }}-webhook-service'
          namespace: '{{ .Release.Namespace }}'
          path: /convert
      conversionReviewVersions:
      - v1
  group: pco.plusserver.com
  names:
    kind: Project
    listKind: ProjectList
    plural: projects
    singular: project
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Project is the Schema for the projects API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ProjectSpec defines the desired state of Project
            properties:
              description:
                type: string
              quotas:
                description: Enabled     *bool            `json:"enabled,omitempty"`
                properties:
                  compute:
                    description: ComputeQuotas defines model for ComputeQuotas.
                    properties:
                      cores:
                        description: Number of cores between 0 and 500
                        type: integer
                      fixed_ips:
                        type: integer
                      floating_ips:
                        description: The number of allowed floating IP addresses for
                          each project
                        type: integer
                      injected_file_content_bytes:
                        type: integer
                      injected_file_path_bytes:
                        type: integer
                      injected_files:
                        type: integer
                      instances:
                        type: integer
                      key_pairs:
                        type: integer
                      metadata_items:
                        type: integer
                      ram:
                        description: Maximum amount of RAM in MiB
                        type: integer
                      security_group_rules:
                        type: integer
                      security_groups:
                        type: integer
                      server_group_members:
                        type: integer
                      server_groups:
                        type: integer
                    required:
                    - instances
                    - key_pairs
                    - metadata_items
                    - server_groups
                    type: object
                  network:
                    description: NetworkQuotas defines model for NetworkQuotas.
                    properties:
                      floatingip:
                        description: The number of floating IP addresses allowed for
                          each project.A value of -1 means no limit
                        type: integer
                      network:
                        type: integer
                      port:
                        type: integer
                      rbac_policy:
                        description: The number of role-based access control (RBAC)
                          policies for each project
                        type: integer
                      router:
                        type: integer
                      security_group:
                        type: integer
                      security_group_rule:
                        type: integer
                      subnet:
                        type: integer
                      subnetpool:
                        type: integer
                    required:
                    - network
                    - router
                    - security_group
                    - security_group_rule
                    - subnet
                    type: object
                  volume:
                    description: VolumeQuotas defines model for VolumeQuotas.
                    properties:
                      backup_gigabytes:
                        type: integer
                      backups:
                        type: integer
                      gigabytes:
                        description: Maximum amount of available Storage
                        type: integer
                      groups:
                        type: integer
                      per_volume_gigabytes:
                        type: integer
                      snapshots:
                        description: Maximum amount of snapshots
                        type: integer
                      volumes:
                        type: integer
                    required:
                    - backup_gigabytes
                    - backups
                    - volumes
                    type: object
                type: object
              region:
                type: string
            type: object
          status:
            description: ProjectStatus defines the observed state of Project
            properties:
              conditions:
                items:
                  description: "Condition contains details for one aspect of the current
                    state of this API Resource. --- This struct is intended for direct
                    use as an array at the field path .status.conditions.  For example,
                    \n type FooStatus struct{ // Represents the observations of a foo's
                    current state. // Known .status.conditions.type are: \"Available\",
                    \"Progressing\", and \"Degraded\" // +patchMergeKey=type // +patchStrategy=merge
                    // +listType=map // +listMapKey=type Conditions []metav1.Condition
                    `json:\"conditions,omitempty\" patchStrategy:\"merge\" patchMergeKey:\"type\"
                    protobuf:\"bytes,1,rep,name=conditions\"` \n // other fields }"
                  properties:
                    lastTransitionTime:
                      description: lastTransitionTime is the last time the condition
                        transitioned from one status to another. This should be when
                        the underlying condition changed.  If that is not known, then
                        using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: message is a human readable message indicating details
                        about the transition. This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: observedGeneration represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.conditions[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: reason contains a programmatic identifier indicating
                        the reason for the condition's last transition. Producers of
                        specific condition types may define expected values and meanings
                        for this field, and whether the values are considered a guaranteed
                        API. The value should be a CamelCase string. This field may
                        not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                        --- Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important. The regex it matches is (dns1123SubdomainFmt/)?(qualifiedNameFmt)
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
            required:
            - conditions
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []